spring:
  application:
    name: error-handling
server:
  port: 9191
  shutdown: graceful
logging:
  level:
    root: WARN
    org.springframework.web: INFO
    ir.bigz.kafka: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss}  [%thread] %-5level %logger{36} - %msg%n"

app:
  topic:
    custom:
      name: kafka-blocking-retry
  restricted:
    ips: "32.241.244.236,15.55.49.164,81.1.95.253,126.130.43.183"
kafka:
  properties:
    bootstrap-server: 172.21.0.2:9092
    retries: 3
    delivery-timeout: 30000
    retry-backoff: 1000
    enable-idempotence: true
    acks: all
    max-in-flight-requests-per-connection: 5
    trusted-package: ir.bigz.kafka.dto
    consumer-group-id: consume-non-blocking-group
    topic-name: kafka-error-handle
    auto-offset-reset: latest