spring:
  application:
    name: producer
  profiles:
    active: production
#  kafka:
#    producer:
#      bootstrap-servers: 172.21.0.2:9092
server:
  port: 9191
  shutdown: graceful
logging:
  level:
    root: WARN
    org.springframework.web: INFO
    ir.bigz.kafka: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss}  [%thread] %-5level %logger{36} - %msg%n"
Kafka:
  config:
    bootstrap-server: 172.21.0.2:9092
